In [1]:
import sys
sys.path.append('/home/s/ss645/sound-separation/')
from glob import glob
from os.path import join
from models.train.data_io import read_lines_from_file
from models.train import mixit
import tensorflow.compat.v1 as v1
from models.train.data_io import wavs_to_dataset

In [2]:
!bash models/neurips2020_mixit/run_train_model_on_fuss.sh

Checking TensorFlow installation...
2022-09-27 14:16:47.099780: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-09-27 14:16:47.099924: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (login-1): /proc/driver/nvidia/version does not exist
tf.Tensor(-1800.4105, shape=(), dtype=float32)
TensorFlow is working, starting training...
Start time : 14:16:47
INFO:tensorflow:Params: dict_values([8, 1, 16000])
INFO:tensorflow:{'feature_spec': {'receiver_audio': FixedLenFeature(shape=[1, 16000], dtype=tf.float32, default_value=None), 'source_images': FixedLenFeature(shape=[8, 1, 16000], dtype=tf.float32, default_value=None)}, 'inference_spec': {'receiver_audio': FixedLenFeature(shape=[1, None], dtype=tf.float32, default_value=None)}, 'hparams': HParams(mix_weights_type='pred_source', signal_names=['mix1_background', 'mix1_foreground_1', 'mix1_

In [3]:
audio_dir = '/research/mc232/sound_datasets/tag-new/audio/'
file_list = glob(join(audio_dir, '*/*/*/*.wav'))
print(len(file_list))

with open(join(audio_dir, 'train_example_list.txt'), 'w') as f:
    for file in file_list[:100]:
        f.write(file)

with open(join(audio_dir, 'validation_example_list.txt'), 'w') as f:
    for file in file_list[100:200]:
        f.write(file)


4988637


In [ ]:
with open(join(audio_dir, 'train_example_list.txt'), 'r') as f:
    lines = f.readlines()
lines[0]

In [7]:
wavs_to_dataset(file_list[:100], 3, 16000)

{'receiver_audio': <tf.Tensor: shape=(3, 1, 16000), dtype=float32, numpy=
 array([[[-0.02255249, -0.04876709, -0.05441284, ..., -0.17559814,
          -0.10534668, -0.10916138]],
 
        [[-0.03451538, -0.03768921, -0.03683472, ..., -0.05770874,
          -0.04794312, -0.04370117]],
 
        [[ 0.11172485,  0.10140991,  0.10397339, ...,  0.39575195,
           0.3993225 ,  0.41448975]]], dtype=float32)>,
 'source_images': <tf.Tensor: shape=(3, 1, 1, 16000), dtype=float32, numpy=
 array([[[[-0.02255249, -0.04876709, -0.05441284, ..., -0.17559814,
           -0.10534668, -0.10916138]]],
 
 
        [[[-0.03451538, -0.03768921, -0.03683472, ..., -0.05770874,
           -0.04794312, -0.04370117]]],
 
 
        [[[ 0.11172485,  0.10140991,  0.10397339, ...,  0.39575195,
            0.3993225 ,  0.41448975]]]], dtype=float32)>}

In [ ]:
fuss_dir = '/research/mc232/sound_datasets/fuss_dev/ssdata'
with open(join(fuss_dir, 'validation_example_list.txt'), 'r') as f:
    lines = f.readlines()

In [4]:
lines[:5]

['validation/example0000.wav\tvalidation/example0000_sources/background0_sound.wav\n',
 'validation/example0001.wav\tvalidation/example0001_sources/background0_sound.wav\tvalidation/example0001_sources/foreground0_sound.wav\n',
 'validation/example0002.wav\tvalidation/example0002_sources/background0_sound.wav\tvalidation/example0002_sources/foreground0_sound.wav\tvalidation/example0002_sources/foreground1_sound.wav\tvalidation/example0002_sources/foreground2_sound.wav\n',
 'validation/example0003.wav\tvalidation/example0003_sources/background0_sound.wav\tvalidation/example0003_sources/foreground0_sound.wav\tvalidation/example0003_sources/foreground1_sound.wav\tvalidation/example0003_sources/foreground2_sound.wav\n',
 'validation/example0004.wav\tvalidation/example0004_sources/background0_sound.wav\tvalidation/example0004_sources/foreground0_sound.wav\tvalidation/example0004_sources/foreground1_sound.wav\n']